basic.forever(function () {
    pins.servoWritePin(AnalogPin.P1, 90)
    pins.servoWritePin(AnalogPin.P2, 0)
    pins.servoWritePin(AnalogPin.P3, 90)
    pins.servoWritePin(AnalogPin.P4, 90)
    basic.pause(5000)
    pins.servoWritePin(AnalogPin.P4, 0)
    basic.pause(1000)
    pins.servoWritePin(AnalogPin.P1, 58)
    basic.pause(1000)
    pins.servoWritePin(AnalogPin.P3, 17)
    basic.pause(1000)
    pins.servoWritePin(AnalogPin.P1, 180)
    basic.pause(1000)
    pins.servoWritePin(AnalogPin.P4, 65)
    basic.pause(1000)
    pins.servoWritePin(AnalogPin.P2, 33)
    basic.pause(1000)
    pins.servoWritePin(AnalogPin.P1, 80)
    basic.pause(1000)
    pins.servoWritePin(AnalogPin.P4, 33)
    basic.pause(1000)
    pins.servoWritePin(AnalogPin.P3, 90)
    basic.pause(1000)
})
